### ISSUE TITLE
Maven-Artifact

### ISSUE THREAD

**Issue by wapolinar** [ionos-enterprise/ionos-enterprise-sdk-java#18]
Although it is described in the documentation, the profitbricks API is not yet available in the "official" maven repository. It is therefore not possible to add it to a project via:

```
<dependency>
    <groupId>com.profitbricks.rest.client</groupId>
    <artifactId>profitbricks-sdk-Java</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>
```

Nevertheless, there is a jCloud labs artifact for profitbricks available there (which might not be directly supported by Profitbricks):

```
<dependency>
    <groupId>org.apache.jclouds.labs</groupId>
    <artifactId>profitbricks</artifactId>
    <version>1.9.2</version>
</dependency>
```

Are you planning to make this SDK available via a public maven repository?

**Comment by jasminSPC** [comment]
Thank you for your suggestions.

Yes we are planning to host the SDK on maven repositories.

On Mon, Jul 11, 2016 at 11:37 AM, Wolfgang Apolinarski <
notifications@github.com> wrote:

> Although it is described in the documentation, the profitbricks API is not
> yet available in the "official" maven repository. It is therefore not
> possible to add it to a project via:
>
> <dependency>
>     <groupId>com.profitbricks.rest.client</groupId>
>     <artifactId>profitbricks-sdk-Java</artifactId>
>     <version>1.0-SNAPSHOT</version>
> </dependency>
>
> Nevertheless, there is a jCloud labs artifact for profitbricks available
> there (which might not be directly supported by Profitbricks):
>
> <dependency>
>     <groupId>org.apache.jclouds.labs</groupId>
>     <artifactId>profitbricks</artifactId>
>     <version>1.9.2</version>
> </dependency>
>
> Are you planning to make this SDK available via a public maven repository?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/profitbricks/profitbricks-sdk-java/issues/18>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AH8SRwceKN5MzZAXbTMeloxnHftq0FnPks5qUg7RgaJpZM4JJMJ4>
> .
>



-- 
Jasmin Gacić
